import { useState } from 'react';
import type { Finding } from '../lib/api';
import {
  domainLabel,
  severityColor,
  severityGlyph,
  severityLabel,
  shortDate,
} from '../lib/format';

/**
 * A One Health finding.
 *
 * The card is built around one idea: **the same fact demands different responses
 * from different people.** A resident needs to know whether to let a dog into
 * the water. A municipal officer needs to know whether to inspect an outfall. A
 * public health officer needs to know whether the exposure warrants
 * surveillance. A single narrative written for all three serves none of them, so
 * the audience is a control rather than an editorial compromise.
 *
 * Everything below the headline is evidence: the facts that fired the rule, the
 * exact values behind them, and the standard each threshold came from. No claim
 * here was generated by a language model — the rule engine decides what is true,
 * and this component only renders it.
 */

type Audience = 'citizen' | 'municipal' | 'health';

const AUDIENCES: { key: Audience; label: string }[] = [
  { key: 'citizen', label: 'Citizen' },
  { key: 'municipal', label: 'Municipality' },
  { key: 'health', label: 'Public health' },
];

export function FindingCard({ finding, showSite }: { finding: Finding; showSite?: boolean }) {
  const [audience, setAudience] = useState<Audience>('citizen');
  const [showEvidence, setShowEvidence] = useState(false);

  const action = {
    citizen: finding.actionCitizen,
    municipal: finding.actionMunicipal,
    health: finding.actionHealth,
  }[audience];

  return (
    <article className="finding">
      <div className="finding-head">
        {/* Glyph plus label — a status colour never carries the meaning alone. */}
        <div
          className="finding-icon"
          style={{ background: severityColor(finding.severity) }}
          aria-hidden="true"
        >
          {severityGlyph(finding.severity)}
        </div>
        <div style={{ minWidth: 0, flex: 1 }}>
          <h3 className="finding-headline">{finding.headline}</h3>
          <p className="finding-mech">{finding.mechanism}</p>
          <div className="finding-tags">
            <span className="tag">{severityLabel(finding.severity)}</span>
            <span className="tag">{domainLabel(finding.domain)}</span>
            <span className="tag">Rule confidence: {finding.confidence}</span>
            <span className="tag">{shortDate(finding.day)}</span>
            {showSite && finding.siteName && <span className="tag">{finding.siteName}</span>}
          </div>
        </div>
      </div>

      <div className="finding-body">
        <div className="audience-tabs" role="group" aria-label="Recommended action for">
          {AUDIENCES.map((option) => (
            <button
              key={option.key}
              type="button"
              aria-pressed={audience === option.key}
              onClick={() => setAudience(option.key)}
            >
              {option.label}
            </button>
          ))}
        </div>

        <p className="action-text">{action}</p>

        <details
          open={showEvidence}
          onToggle={(event) => setShowEvidence((event.currentTarget as HTMLDetailsElement).open)}
          style={{ marginTop: 11 }}
        >
          <summary
            style={{
              cursor: 'pointer',
              fontSize: 12,
              color: 'var(--text-secondary)',
              padding: '3px 0',
            }}
          >
            Evidence and provenance ({finding.evidence.length} observation
            {finding.evidence.length === 1 ? '' : 's'})
          </summary>

          <ul className="evidence" style={{ marginTop: 7 }}>
            {finding.evidence.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>

          {Object.keys(finding.metrics).length > 0 && (
            <table className="data" style={{ marginTop: 10 }}>
              <caption className="sr-only">Exact values behind this finding</caption>
              <thead>
                <tr>
                  <th scope="col">Measure</th>
                  <th scope="col">Value</th>
                </tr>
              </thead>
              <tbody>
                {Object.entries(finding.metrics).map(([key, value]) => (
                  <tr key={key}>
                    <td>{humanise(key)}</td>
                    <td className="num">{formatMetric(value)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          <p className="citation">
            Rule <code>{finding.ruleId}</code>
            {finding.ruleVersion ? ` v${finding.ruleVersion}` : ''} — produced by a deterministic
            rule, not a language model.
            {finding.citations.length > 0 && (
              <>
                <br />
                Thresholds from: {finding.citations.join(' · ')}
              </>
            )}
          </p>
        </details>
      </div>
    </article>
  );
}

/** camelCase metric keys into something a non-developer can read. */
function humanise(key: string): string {
  const spaced = key.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase());
  return spaced
    .replace(/Mgl/g, '(mg/L)')
    .replace(/Mm/g, '(mm)')
    .replace(/Pct/g, '(%)')
    .replace(/C$/, '(°C)');
}

function formatMetric(value: number): string {
  if (!Number.isFinite(value)) return '—';
  if (Number.isInteger(value)) return String(value);
  return Math.abs(value) < 1 ? value.toFixed(3) : value.toFixed(2);
}
