import type { ResponseMeta } from '@neer/shared';
import { METHOD_VERSION } from '@neer/scoring';

/**
 * The response envelope's metadata block.
 *
 * `dataDisclosure` ships on every payload rather than being documented
 * somewhere a consumer might not read. A client cannot obtain Neer data without
 * also obtaining the statement of what is measured and what is modelled, which
 * makes honest presentation the default rather than an act of diligence by
 * whoever builds the UI.
 */
export function buildMeta(asOf: string | null = null): ResponseMeta {
  return {
    asOf: asOf ?? new Date().toISOString(),
    methodVersion: METHOD_VERSION,
    dataDisclosure: {
      observations: 'simulated',
      environmental: 'real',
      note:
        'Citizen observations in this deployment are synthetic, generated by a documented physical model. ' +
        'Weather and hydrology are real measurements from Open-Meteo. Site locations are approximate ' +
        'representative points on real watercourses near Coimbra, Portugal. No value here describes the ' +
        'measured condition of any real stream.',
    },
  };
}

export const envelope = <T>(data: T, asOf: string | null = null) => ({
  data,
  meta: buildMeta(asOf),
});
