import { z } from 'zod';
import { FindingDomain, RuleConfidence, Severity } from './enums';

/**
 * A One Health finding: a structured, evidence-bearing statement produced by a
 * deterministic rule.
 *
 * Findings are never generated by a language model. The rule engine decides what
 * is true; language generation, where it is used at all, only renders an already
 * decided finding into prose. That boundary is the core safety property of this
 * system — a fabricated pathogen-risk statement attached to a public waterway
 * either triggers an unwarranted closure or fails to trigger a warranted one,
 * and neither failure is acceptable from a system nobody can audit.
 *
 * Auditability is therefore structural, not a feature: `ruleId` identifies the
 * logic, `metrics` carries the exact values that fired it, and `citations` names
 * the standard or study each threshold came from. Any claim this system makes
 * can be traced back to a number and a source.
 */
export const FindingSchema = z.object({
  findingId: z.string().uuid(),
  siteId: z.string(),
  day: z.string(),

  ruleId: z.string(),
  ruleVersion: z.string(),

  domain: FindingDomain,
  severity: Severity,
  confidence: RuleConfidence,

  /** One line, stated as a fact about the world, not about the data. */
  headline: z.string(),
  /** The causal story the rule asserts, in one sentence. */
  mechanism: z.string(),
  /** Human-readable facts that caused the rule to fire. */
  evidence: z.array(z.string()),
  /** The exact values behind the evidence, for audit and replay. */
  metrics: z.record(z.string(), z.number()),
  /** Standards or studies the thresholds derive from. */
  citations: z.array(z.string()),

  /**
   * The same fact demands different responses from different people. A resident
   * needs to know whether to let a dog into the water; a municipal officer needs
   * to know whether to inspect an outfall; a public health officer needs to know
   * whether the exposure warrants surveillance. A single narrative written for
   * all three serves none of them.
   */
  actions: z.object({
    citizen: z.string(),
    municipal: z.string(),
    health: z.string(),
  }),

  detectedAt: z.string(),
  validUntil: z.string(),
});
export type Finding = z.infer<typeof FindingSchema>;

/** A finding joined to its site, as returned by the alerts endpoint. */
export const FindingWithSiteSchema = FindingSchema.extend({
  siteName: z.string(),
  catchment: z.string(),
  lat: z.number(),
  lon: z.number(),
});
export type FindingWithSite = z.infer<typeof FindingWithSiteSchema>;

/**
 * The inputs a rule is evaluated against.
 *
 * Assembled once per site-day and passed to every rule, so rules stay pure
 * functions of this context — no database access, no clock, no network. That
 * makes the entire rule set testable by constructing a context literal, which is
 * the only practical way to get coverage over threshold boundaries.
 */
export const RuleContextSchema = z.object({
  siteId: z.string(),
  day: z.string(),

  site: z.object({
    name: z.string(),
    catchment: z.string(),
    urbanClass: z.string(),
    combinedSewer: z.boolean(),
    recreationalAccess: z.boolean(),
    nearestContactM: z.number(),
    populationWithin1km: z.number(),
    imperviousPct: z.number(),
    referenceDoMgl: z.number(),
  }),

  /** Current-day measurements, null where not measured. */
  current: z.record(z.string(), z.number().nullable()),
  /** Rolling 7-day means, for trend-aware rules. */
  ma7: z.record(z.string(), z.number().nullable()),
  /** Rolling 30-day means, the baseline a 7-day mean is compared against. */
  ma30: z.record(z.string(), z.number().nullable()),

  /** Weather and hydrology context for the day. */
  env: z.object({
    tempMeanC: z.number().nullable(),
    tempMaxC: z.number().nullable(),
    precipMm: z.number().nullable(),
    precip48hMm: z.number().nullable(),
    precip7dMm: z.number().nullable(),
    dryDaysBefore: z.number().nullable(),
    dischargeM3s: z.number().nullable(),
    /** Consecutive days at or above 25 °C, a bloom and thermal-stress precondition. */
    consecutiveHotDays: z.number(),
  }),

  /** The computed index for the day, so rules can reason about the score itself. */
  health: z.object({
    sohi: z.number(),
    ecologicalScore: z.number(),
    pressureScore: z.number(),
    exposureScore: z.number(),
    confidence: z.number(),
    sohiDelta7d: z.number().nullable(),
    sohiDelta30d: z.number().nullable(),
  }),

  nObs: z.number().int(),
  daysSinceLastObs: z.number().int(),
});
export type RuleContext = z.infer<typeof RuleContextSchema>;
